name: Build Image Dev

on:
  workflow_dispatch: {}
  push:
    branches:
      - '*'
      - '!main'
    paths: 
      - 'mlflow-server/**'
      - '.github/**'

jobs:
  get-version:
    uses: ./.github/workflows/workflow-get-package-version.yaml
    with: 
      context: "mlflow-server"
      package: mlflow

  build:
    uses: ./.github/workflows/workflow-build-image.yaml
    needs: get-version
    with:
      registry: quay.io/troyer
      image-name: mlflow-server
      context: "mlflow-server"
      version-tag: ${{ needs.get-version.outputs.package-version }}
      tag-suffix: "-dev"
    secrets:
      registry-username: ${{ secrets.QUAY_USERNAME }}
      registry-password: ${{ secrets.QUAY_PASSWORD }}
